#ifndef SUPERSERPENT_PARAMS_H
#define SUPERSERPENT_PARAMS_H

#define BLOCK_SIZE_SLOTH 16    // 128-bit (16 bytes) block size for serpent
#define ITERATIONS_SLOTH 10000 // PBKDF2 迭代次数
#define MAX_INPUT_LEN_SLOTH 1024
#define GCM_BLOCK_SIZE_SLOTH 10*1024*1024
#define SALT_SIZE_SLOTH 16
#define IV_SIZE_SLOTH 16
#define NONCE_SIZE_SLOTH 12
#define TAG_SIZE_SLOTH 16
#define KEY_SIZE_SLOTH 32
#define BLOCK_SIZE_WHIRLPOOL_SLOTH 64   // 512-bit Whirlpool 使用的块大小
#define OUTPUT_SIZE_SLOTH 64  // 512-bit Whirlpool 哈希输出大小
#define PWD_MAX_LENGTH_SLOTH 256
#define PLAINTEXT_MAX_LENGTH_SLOTH 1024
#define PADDEDTEXT_MAX_LENGTH_SLOTH 2048
#define HEXINPUT_MAX_LENGTH_SLOTH 4096
#define ROUTE_LENGTH_SLOTH 256
#define SERPENT_KSSIZE_SLOTH 560 //140 * 4
#endif