name: CMake Build

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 CMake
        run: sudo apt update && sudo apt install -y cmake g++ ninja-build

      - name: 创建构建目录
        run: mkdir -p build

      - name: 运行 CMake 生成构建文件
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: 编译项目
        run: cmake --build build --config Release
